'use strict';

// Generated by listing-sync (infra scripts/listing_sync/connectors/zapier.py); edits are overwritten.
const api = require('./lib/api');

module.exports = {
  version: require('./package.json').version,
  platformVersion: require('zapier-platform-core').version,

  authentication: {
    type: 'custom',
    fields: [
      {
        "key": "api_key",
        "label": "API Key",
        "type": "password",
        "required": true,
        "helpText": "Create a key at [flatmark.dev](https://flatmark.dev/go/zapier?to=/app/api-keys)."
      },
    ],
    test: api.testAuth,
  },

  beforeRequest: [api.addApiKey],

  creates: {
    get_me: require('./creates/get_me'),
    get_job: require('./creates/get_job'),
    list_jobs: require('./creates/list_jobs'),
    convert_document: require('./creates/convert_document'),
    submit_conversion_job: require('./creates/submit_conversion_job'),
    get_conversion_result: require('./creates/get_conversion_result'),
  },
};
