'use strict';

// Generated by listing-sync (infra scripts/listing_sync/connectors/zapier.py); edits are overwritten.
const api = require('../lib/api');

const REQUEST = {
  "method": "POST",
  "path": "/v1/convert",
  "body": "form",
  "output": "json",
  "fields": [
    {
      "name": "file",
      "location": "file",
      "type": "string"
    }
  ]
};

const DEFINITION = {
  "key": "convert_document",
  "noun": "flatmark",
  "display": {
    "label": "Convert a document to Markdown in one call",
    "description": "Converts one document up to 8 MB and returns the Markdown in the response."
  },
  "operation": {
    "inputFields": [
      {
        "key": "file",
        "label": "File",
        "required": true,
        "type": "file",
        "helpText": "The document, sent as multipart form data with its Content-Type."
      }
    ],
    "sample": {
      "markdown": "sample",
      "meta": {}
    }
  }
};

module.exports = {
  ...DEFINITION,
  operation: {
    ...DEFINITION.operation,
    perform: (z, bundle) => api.call(z, REQUEST, bundle.inputData),
  },
};
