'use strict';

// Generated by listing-sync (infra scripts/listing_sync/connectors/zapier.py); edits are overwritten.
const api = require('../lib/api');

const REQUEST = {
  "method": "GET",
  "path": "/v1/jobs/{job_id}",
  "body": null,
  "output": "json",
  "fields": [
    {
      "name": "job_id",
      "location": "path",
      "type": "string"
    }
  ]
};

const DEFINITION = {
  "key": "get_job",
  "noun": "flatmark",
  "display": {
    "label": "Get one queued job by ID",
    "description": "Returns one of your jobs. An unknown ID, or a job owned by someone else, returns 404."
  },
  "operation": {
    "inputFields": [
      {
        "key": "job_id",
        "label": "Job id",
        "required": true,
        "type": "string",
        "helpText": "The `job_id` from the submit response."
      }
    ],
    "sample": {
      "id": "sample",
      "kind": "sample",
      "status": "sample",
      "result": {},
      "error": "sample",
      "created_at": "sample",
      "started_at": "sample",
      "finished_at": "sample"
    }
  }
};

module.exports = {
  ...DEFINITION,
  operation: {
    ...DEFINITION.operation,
    perform: (z, bundle) => api.call(z, REQUEST, bundle.inputData),
  },
};
