'use strict';

// Generated by listing-sync (infra scripts/listing_sync/connectors/zapier.py); edits are overwritten.
const api = require('../lib/api');

const REQUEST = {
  "method": "GET",
  "path": "/v1/jobs",
  "body": null,
  "output": "json",
  "fields": [
    {
      "name": "limit",
      "location": "query",
      "type": "integer"
    },
    {
      "name": "cursor",
      "location": "query",
      "type": "string"
    }
  ]
};

const DEFINITION = {
  "key": "list_jobs",
  "noun": "flatmark",
  "display": {
    "label": "List your queued jobs, newest first",
    "description": "Lists your jobs, newest first. Pass `next_cursor` back as `cursor` to get the next page."
  },
  "operation": {
    "inputFields": [
      {
        "key": "limit",
        "label": "Limit",
        "required": false,
        "type": "integer",
        "helpText": "Items per page.",
        "default": "50"
      },
      {
        "key": "cursor",
        "label": "Cursor",
        "required": false,
        "type": "string",
        "helpText": "The `next_cursor` from the previous page."
      }
    ],
    "sample": {
      "items": [],
      "next_cursor": "sample"
    }
  }
};

module.exports = {
  ...DEFINITION,
  operation: {
    ...DEFINITION.operation,
    perform: (z, bundle) => api.call(z, REQUEST, bundle.inputData),
  },
};
