'use strict';

// Generated by listing-sync (infra scripts/listing_sync/connectors/zapier.py); edits are overwritten.
const api = require('../lib/api');

const REQUEST = {
  "method": "POST",
  "path": "/v1/convert/jobs",
  "body": "form",
  "output": "json",
  "fields": [
    {
      "name": "file",
      "location": "file",
      "type": "string"
    },
    {
      "name": "webhook_url",
      "location": "form",
      "type": "string"
    }
  ]
};

const RESULT = {
  "method": "GET",
  "path": "/v1/convert/jobs/{job_id}/result",
  "body": null,
  "output": "text",
  "fields": [
    {
      "name": "job_id",
      "location": "path",
      "type": "string"
    },
    {
      "name": "format",
      "location": "query",
      "type": "string"
    }
  ]
};

const DEFINITION = {
  "key": "submit_conversion_job",
  "noun": "flatmark",
  "display": {
    "label": "Queue a document for conversion with OCR and tables",
    "description": "Queues one document up to 25 MB and 200 pages for conversion with Docling."
  },
  "operation": {
    "inputFields": [
      {
        "key": "file",
        "label": "File",
        "required": true,
        "type": "file",
        "helpText": "The document, sent as multipart form data with its Content-Type."
      }
    ],
    "sample": {
      "job_id": "sample",
      "text": "sample",
      "content_type": "text/markdown"
    }
  }
};

module.exports = {
  ...DEFINITION,
  operation: {
    ...DEFINITION.operation,
    // The API POSTs the job's final state to Zapier's callback URL.
    perform: (z, bundle) =>
      api.call(z, REQUEST, {
        ...bundle.inputData,
        webhook_url: z.generateCallbackUrl(),
      }),
    performResume: (z, bundle) => api.resume(z, bundle, RESULT),
  },
};
