/* globals describe, expect, test */
'use strict';

// Generated by listing-sync (infra scripts/listing_sync/connectors/zapier.py); edits are overwritten.
// Live calls need a key (API_KEY=... npm test) and spend its credits; a
// binary answer is stashed as a Zapier file, which also needs ZAPIER_DEPLOY_KEY.
const zapier = require('zapier-platform-core');

const App = require('../index');

const appTester = zapier.createAppTester(App);
zapier.tools.env.inject();

const live = process.env.API_KEY ? test : test.skip;
const liveFile = process.env.API_KEY && process.env.ZAPIER_DEPLOY_KEY ? test : test.skip;
const authData = { api_key: process.env.API_KEY };

describe('authentication', () => {
  live('accepts the key', async () => {
    const result = await appTester(App.authentication.test, { authData });
    expect(result).toBeTruthy();
  });
});

describe('creates', () => {
  live('get_me', async () => {
    const inputData = {};
    const result = await appTester(App.creates.get_me.operation.perform, {
      authData,
      inputData,
    });
    expect(Object.keys(result).length).toBeGreaterThan(0);
  });

  test('get_job is defined (its input comes from an earlier step)', () => {
    expect(typeof App.creates.get_job.operation.perform).toBe('function');
  });

  live('list_jobs', async () => {
    const inputData = {};
    const result = await appTester(App.creates.list_jobs.operation.perform, {
      authData,
      inputData,
    });
    expect(Object.keys(result).length).toBeGreaterThan(0);
  });

  live('convert_document', async () => {
    const inputData = {
      "file": "https://flatmark.dev/app-static/samples/sample.pdf"
    };
    const result = await appTester(App.creates.convert_document.operation.perform, {
      authData,
      inputData,
    });
    expect(Object.keys(result).length).toBeGreaterThan(0);
  });

  live('submit_conversion_job', async () => {
    const inputData = {
      "file": "https://flatmark.dev/app-static/samples/sample.pdf"
    };
    const result = await appTester(App.creates.submit_conversion_job.operation.perform, {
      authData,
      inputData,
    });
    expect(Object.keys(result).length).toBeGreaterThan(0);
  });

  test('get_conversion_result is defined (its input comes from an earlier step)', () => {
    expect(typeof App.creates.get_conversion_result.operation.perform).toBe('function');
  });
});
