// Generated by listing-sync from https://api.flatmark.dev/openapi.json — do not edit.
import type {
	IDataObject,
	IExecuteFunctions,
	IHttpRequestMethods,
	IN8nHttpFullResponse,
	INodeExecutionData,
	INodeType,
	INodeTypeDescription,
	JsonObject,
} from 'n8n-workflow';
import {
	jsonParse,
	NodeApiError,
	NodeConnectionTypes,
	NodeOperationError,
	sleep,
} from 'n8n-workflow';

const BASE_URL = 'https://api.flatmark.dev';
const CREDENTIAL = 'flatmarkApi';
const POLL_SECONDS = 5;
const POLL_LIMIT = 360;

type Location = 'path' | 'query' | 'json' | 'form' | 'file';

interface ApiField {
	name: string;
	param: string;
	location: Location;
	type: string;
	required: boolean;
}

interface ApiOperation {
	method: IHttpRequestMethods;
	path: string;
	body: 'none' | 'json' | 'form';
	fields: ApiField[];
	job?: { poll: string; result: string };
}

function jsonValue(value: unknown): unknown {
	return typeof value === 'string' ? jsonParse(value) : value;
}

async function request(
	ctx: IExecuteFunctions,
	method: IHttpRequestMethods,
	path: string,
	qs: IDataObject = {},
	body?: FormData | IDataObject,
): Promise<IN8nHttpFullResponse> {
	return (await ctx.helpers.httpRequestWithAuthentication.call(ctx, CREDENTIAL, {
		method,
		url: BASE_URL + path,
		qs,
		arrayFormat: 'repeat',
		body,
		encoding: 'arraybuffer',
		returnFullResponse: true,
	})) as IN8nHttpFullResponse;
}

async function send(
	ctx: IExecuteFunctions,
	op: ApiOperation,
	i: number,
): Promise<IN8nHttpFullResponse> {
	const extra = ctx.getNodeParameter('additionalFields', i, {}) as IDataObject;
	const binary = ctx.getInputData()[i].binary ?? {};
	let path = op.path;
	const qs: IDataObject = {};
	const json: IDataObject = {};
	const form = new FormData();
	for (const field of op.fields) {
		const topLevel = field.required || field.location === 'file';
		const value = topLevel ? ctx.getNodeParameter(field.param, i, '') : extra[field.param];
		if (value === undefined || value === '') continue;
		if (field.location === 'file') {
			const property = String(value);
			if (!field.required && !binary[property]) continue;
			const meta = ctx.helpers.assertBinaryData(i, property);
			const buffer = await ctx.helpers.getBinaryDataBuffer(i, property);
			form.append(
				field.name,
				new Blob([new Uint8Array(buffer)], { type: meta.mimeType }),
				meta.fileName ?? field.name,
			);
		} else if (field.location === 'path') {
			path = path.replace(`{${field.name}}`, encodeURIComponent(String(value)));
		} else if (field.location === 'query') {
			qs[field.name] =
				field.type === 'array'
					? String(value)
							.split(',')
							.map((v) => v.trim())
							.filter((v) => v)
					: (value as IDataObject[keyof IDataObject]);
		} else if (field.location === 'json') {
			json[field.name] = (
				field.type === 'object' || field.type === 'array' ? jsonValue(value) : value
			) as IDataObject[keyof IDataObject];
		} else {
			form.append(field.name, String(value));
		}
	}
	const body = op.body === 'form' ? form : op.body === 'json' ? json : undefined;
	return await request(ctx, op.method, path, qs, body);
}

function onePath(path: string, id: string): string {
	return path.replace(/\{[^}]+\}/, encodeURIComponent(id));
}

async function decode(
	ctx: IExecuteFunctions,
	response: IN8nHttpFullResponse,
	i: number,
): Promise<INodeExecutionData> {
	const header = response.headers['content-type'];
	const mimeType = String(Array.isArray(header) ? header[0] : (header ?? '')).split(';')[0].trim();
	const data = Buffer.from(response.body as ArrayBuffer);
	if (mimeType === 'application/json' || mimeType.endsWith('+json')) {
		const parsed = jsonParse<unknown>(data.toString('utf8'));
		const item =
			parsed && typeof parsed === 'object' && !Array.isArray(parsed)
				? (parsed as IDataObject)
				: ({ data: parsed } as IDataObject);
		return { json: item, pairedItem: { item: i } };
	}
	if (mimeType.startsWith('text/') || mimeType.endsWith('xml')) {
		return { json: { data: data.toString('utf8'), mimeType }, pairedItem: { item: i } };
	}
	const disposition = String(response.headers['content-disposition'] ?? '');
	const fileName = /filename="?([^";]+)"?/.exec(disposition)?.[1];
	const file = await ctx.helpers.prepareBinaryData(data, fileName, mimeType || undefined);
	return {
		json: { fileName: file.fileName, mimeType: file.mimeType, fileSize: file.fileSize },
		binary: { data: file },
		pairedItem: { item: i },
	};
}

async function runJob(
	ctx: IExecuteFunctions,
	job: { poll: string; result: string },
	submitted: IDataObject,
	i: number,
): Promise<IN8nHttpFullResponse> {
	const id = String(submitted.job_id ?? submitted.id ?? '');
	const poll = OPERATIONS[job.poll];
	const result = OPERATIONS[job.result];
	for (let attempt = 0; attempt < POLL_LIMIT; attempt++) {
		await sleep(POLL_SECONDS * 1000);
		const state = (await decode(ctx, await request(ctx, poll.method, onePath(poll.path, id)), i))
			.json;
		if (state.status === 'succeeded') {
			return await request(ctx, result.method, onePath(result.path, id));
		}
		if (state.status === 'failed') {
			throw new NodeOperationError(ctx.getNode(), `Job ${id} failed: ${String(state.error ?? '')}`, {
				itemIndex: i,
			});
		}
	}
	throw new NodeOperationError(ctx.getNode(), `Job ${id} did not finish in time`, { itemIndex: i });
}

const OPERATIONS: Record<string, ApiOperation> = {
	get_me: {
		method: 'GET',
		path: '/v1/me',
		body: 'none',
		fields: [],
	},
	get_job: {
		method: 'GET',
		path: '/v1/jobs/{job_id}',
		body: 'none',
		fields: [
			{
				name: 'job_id',
				param: 'jobId',
				location: 'path',
				type: 'string',
				required: true,
			},
		],
	},
	list_jobs: {
		method: 'GET',
		path: '/v1/jobs',
		body: 'none',
		fields: [
			{
				name: 'limit',
				param: 'limit',
				location: 'query',
				type: 'integer',
				required: false,
			},
			{
				name: 'cursor',
				param: 'cursor',
				location: 'query',
				type: 'string',
				required: false,
			},
		],
	},
	convert_document: {
		method: 'POST',
		path: '/v1/convert',
		body: 'form',
		fields: [
			{
				name: 'file',
				param: 'binaryPropertyName',
				location: 'file',
				type: 'string',
				required: true,
			},
		],
	},
	submit_conversion_job: {
		method: 'POST',
		path: '/v1/convert/jobs',
		body: 'form',
		fields: [
			{
				name: 'file',
				param: 'binaryPropertyName',
				location: 'file',
				type: 'string',
				required: true,
			},
			{
				name: 'webhook_url',
				param: 'webhookUrl',
				location: 'form',
				type: 'string',
				required: false,
			},
		],
		job: {
			poll: 'get_job',
			result: 'get_conversion_result',
		},
	},
	get_conversion_result: {
		method: 'GET',
		path: '/v1/convert/jobs/{job_id}/result',
		body: 'none',
		fields: [
			{
				name: 'job_id',
				param: 'jobId',
				location: 'path',
				type: 'string',
				required: true,
			},
			{
				name: 'format',
				param: 'format',
				location: 'query',
				type: 'string',
				required: false,
			},
		],
	},
};

export class Flatmark implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'flatmark',
		name: 'flatmark',
		icon: {
			light: 'file:../../icons/flatmark.svg',
			dark: 'file:../../icons/flatmark.svg',
		},
		group: ['transform'],
		version: 1,
		subtitle: '={{$parameter["operation"] + ": " + $parameter["resource"]}}',
		description: 'Document to Markdown API and MCP server for PDF, Word, PowerPoint, Excel and HTML. OCR queue for large files. Hosted in Germany.',
		defaults: {
			name: 'flatmark',
		},
		usableAsTool: true,
		inputs: [NodeConnectionTypes.Main],
		outputs: [NodeConnectionTypes.Main],
		credentials: [
			{
				name: 'flatmarkApi',
				required: true,
			},
		],
		properties: [
			{
				displayName: 'Resource',
				name: 'resource',
				type: 'options',
				noDataExpression: true,
				options: [
					{
						name: 'Account',
						value: 'account',
					},
					{
						name: 'Flatmark',
						value: 'flatmark',
					},
					{
						name: 'Job',
						value: 'job',
					},
				],
				default: 'flatmark',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: {
					show: {
						resource: ['account'],
					},
				},
				options: [
					{
						name: 'Get Me',
						value: 'get_me',
						description: 'Your plan, remaining requests, and remaining credits',
						action: 'Get me',
					},
				],
				default: 'get_me',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: {
					show: {
						resource: ['job'],
					},
				},
				options: [
					{
						name: 'Get Job',
						value: 'get_job',
						description: 'Get one queued job by ID',
						action: 'Get job',
					},
					{
						name: 'List Jobs',
						value: 'list_jobs',
						description: 'List your queued jobs, newest first',
						action: 'List jobs',
					},
				],
				default: 'get_job',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: {
					show: {
						resource: ['flatmark'],
					},
				},
				options: [
					{
						name: 'Convert Document',
						value: 'convert_document',
						description: 'Convert a document to Markdown in one call',
						action: 'Convert document',
					},
					{
						name: 'Get Conversion Result',
						value: 'get_conversion_result',
						description: 'Download a queued job\'s Markdown or JSON',
						action: 'Get conversion result',
					},
					{
						name: 'Submit Conversion Job',
						value: 'submit_conversion_job',
						description: 'Queue a document for conversion with OCR and tables',
						action: 'Submit conversion job',
					},
				],
				default: 'convert_document',
			},
			{
				displayName: 'Job ID',
				name: 'jobId',
				type: 'string',
				default: '',
				required: true,
				displayOptions: {
					show: {
						resource: ['job'],
						operation: ['get_job'],
					},
				},
				description: 'The \'job_id\' from the submit response',
			},
			{
				displayName: 'Additional Fields',
				name: 'additionalFields',
				type: 'collection',
				placeholder: 'Add Field',
				default: {},
				displayOptions: {
					show: {
						resource: ['job'],
						operation: ['list_jobs'],
					},
				},
				options: [
					{
						displayName: 'Cursor',
						name: 'cursor',
						type: 'string',
						default: '',
						description: 'The \'next_cursor\' from the previous page',
					},
					{
						displayName: 'Limit',
						name: 'limit',
						type: 'number',
						default: 50,
						typeOptions: {
							minValue: 1,
						},
						description: 'Max number of results to return',
					},
				],
			},
			{
				displayName: 'Input Binary Field',
				name: 'binaryPropertyName',
				type: 'string',
				default: 'data',
				hint: 'The name of the input binary field containing the file to be uploaded',
				required: true,
				displayOptions: {
					show: {
						resource: ['flatmark'],
						operation: ['convert_document'],
					},
				},
				description: 'The document, sent as multipart form data with its Content-Type',
			},
			{
				displayName: 'Input Binary Field',
				name: 'binaryPropertyName',
				type: 'string',
				default: 'data',
				hint: 'The name of the input binary field containing the file to be uploaded',
				required: true,
				displayOptions: {
					show: {
						resource: ['flatmark'],
						operation: ['submit_conversion_job'],
					},
				},
				description: 'The document, sent as multipart form data with its Content-Type',
			},
			{
				displayName: 'Additional Fields',
				name: 'additionalFields',
				type: 'collection',
				placeholder: 'Add Field',
				default: {},
				displayOptions: {
					show: {
						resource: ['flatmark'],
						operation: ['submit_conversion_job'],
					},
				},
				options: [
					{
						displayName: 'Webhook URL',
						name: 'webhookUrl',
						type: 'string',
						default: '',
						description: 'Optional. A public http or https URL that receives a POST when the job finishes.',
					},
				],
			},
			{
				displayName: 'Job ID',
				name: 'jobId',
				type: 'string',
				default: '',
				required: true,
				displayOptions: {
					show: {
						resource: ['flatmark'],
						operation: ['get_conversion_result'],
					},
				},
			},
			{
				displayName: 'Additional Fields',
				name: 'additionalFields',
				type: 'collection',
				placeholder: 'Add Field',
				default: {},
				displayOptions: {
					show: {
						resource: ['flatmark'],
						operation: ['get_conversion_result'],
					},
				},
				options: [
					{
						displayName: 'Format',
						name: 'format',
						type: 'options',
						options: [
							{
								name: 'JSON',
								value: 'json',
							},
							{
								name: 'Markdown',
								value: 'markdown',
							},
						],
						default: 'markdown',
						description: '\'markdown\' (default) or \'JSON\' for the DoclingDocument structure file',
					},
				],
			},
		],
	};

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		const items = this.getInputData();
		const out: INodeExecutionData[] = [];
		for (let i = 0; i < items.length; i++) {
			try {
				const op = OPERATIONS[this.getNodeParameter('operation', i) as string];
				let response = await send(this, op, i);
				if (op.job) {
					const submitted = (await decode(this, response, i)).json;
					response = await runJob(this, op.job, submitted, i);
				}
				out.push(await decode(this, response, i));
			} catch (error) {
				if (this.continueOnFail()) {
					out.push({ json: { error: (error as Error).message }, pairedItem: { item: i } });
					continue;
				}
				throw new NodeApiError(this.getNode(), error as JsonObject, { itemIndex: i });
			}
		}
		return [out];
	}
}
