"""flatmark: Convert document. Generated by listing-sync (infra scripts/listing_sync/connectors/dify.py); edits are overwritten."""

from collections.abc import Generator
from typing import Any

from dify_plugin import Tool
from dify_plugin.entities.tool import ToolInvokeMessage

from tools._client import call

OPERATION = {
    "method": "POST",
    "path": "/v1/convert",
    "body": "multipart",
    "fields": [
        {
            "name": "file",
            "location": "file",
            "type": "string"
        }
    ]
}


class ConvertDocumentTool(Tool):
    def _invoke(self, tool_parameters: dict[str, Any]) -> Generator[ToolInvokeMessage]:
        yield from call(self, OPERATION, tool_parameters)
